
SELECT DISTINCT NOME
               ,YEAR([DATA DE NASCIMENTO]) AS ANO_NASCIMENTO
,CASE	  
    WHEN YEAR([DATA DE NASCIMENTO]) <= '1990' THEN 'ADULTO'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN '1990' AND '1995' THEN 'JOVEM'
	WHEN YEAR([DATA DE NASCIMENTO]) >= '1995' THEN 'CRIANÇA'
ELSE 'CLASSIFICAR DATA'
END AS CATEGORIA
FROM [TABELA DE CLIENTES]