SELECT NOME, IMPOSTO
,CASE
    WHEN IMPOSTO = 0.1 THEN 'FAIXA 1'
	WHEN IMPOSTO = 0.12 THEN 'FAIXA 2'
	ELSE 'CLASSIFICAR'
	END AS CATEGORIA_IMPOSTO
FROM [NOTAS FISCAIS]

INNER JOIN [TABELA DE CLIENTES]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF

GROUP BY NOME, IMPOSTO,
CASE
    WHEN IMPOSTO = 0.1 THEN 'FAIXA 1'
	WHEN IMPOSTO = 0.12 THEN 'FAIXA 2'
	ELSE 'CLASSIFICAR'
	END

HAVING 
COUNT(CASE
    WHEN IMPOSTO = 0.1 THEN 'FAIXA 1'
	WHEN IMPOSTO = 0.12 THEN 'FAIXA 2'
	ELSE 'CLASSIFICAR'
	END) = 'FAIXA 2'

ORDER BY NOME DESC





SELECT COUNT(IMPOSTO),
CASE 
WHEN IMPOSTO = 0.1 THEN 'FAIXA 1'
WHEN IMPOSTO = 0.12 THEN 'FAIXA 2'
ELSE 'CLASSIFICAR'
END AS CAT_IMPOSTO
FROM [NOTAS FISCAIS]
GROUP BY CASE 
WHEN IMPOSTO = 0.1 THEN 'FAIXA 1'
WHEN IMPOSTO = 0.12 THEN 'FAIXA 2'
ELSE 'CLASSIFICAR'
END



