SELECT [NOME DO PRODUTO]
      ,SUM([QUANTIDADE]) AS SOMA_QTD
from [ITENS NOTAS FISCAIS]
INNER JOIN [TABELA DE PRODUTOS] 
ON [ITENS NOTAS FISCAIS].[CODIGO DO PRODUTO] = [TABELA DE PRODUTOS].[CODIGO DO PRODUTO]
GROUP BY [NOME DO PRODUTO]
HAVING [NOME DO PRODUTO] LIKE 'LINHA%' OR [NOME DO PRODUTO] LIKE '%%LIGHT'
ORDER BY 2 DESC
