USE NOME DO BANCO DE DADOS;
GO
BULK INSERT NOME DA TABELA(TIPOS DE DADOS ATRIBUTOS DA TABELA = TIPOS DE DADOS ATRIBUTOS ARQUIVO FROM 'diretório do arquivo csv'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);
GO